language: rust
rust:
  - stable
cache: cargo
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
deploy:
  provider: pages
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
